server:
  port: 8000
spring:
  profiles:
    - dev
  application:
    name: admin-service
  security:
    user:
      password: P@ssword1@


logging:
  file:
    name: E://springbootLogs//admin-service.log
---
server:
  port: 9000
spring:
  profiles:
    - test
  application:
    name: admin-service
  cloud:
    config:
      uri: http://localhost:9999